/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrganiserRouteImport } from './routes/organiser'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminEntryRouteImport } from './routes/admin.entry'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserRoute = OrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntryRoute = AdminEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/organiser': typeof OrganiserRoute
  '/scanner': typeof ScannerRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/entry': typeof AdminEntryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/organiser': typeof OrganiserRoute
  '/scanner': typeof ScannerRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/entry': typeof AdminEntryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/organiser': typeof OrganiserRoute
  '/scanner': typeof ScannerRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/entry': typeof AdminEntryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/organiser'
    | '/scanner'
    | '/admin/codes'
    | '/admin/entry'
    | '/admin/logs'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/organiser'
    | '/scanner'
    | '/admin/codes'
    | '/admin/entry'
    | '/admin/logs'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/organiser'
    | '/scanner'
    | '/admin/codes'
    | '/admin/entry'
    | '/admin/logs'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  OrganiserRoute: typeof OrganiserRoute
  ScannerRoute: typeof ScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser': {
      id: '/organiser'
      path: '/organiser'
      fullPath: '/organiser'
      preLoaderRoute: typeof OrganiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entry': {
      id: '/admin/entry'
      path: '/entry'
      fullPath: '/admin/entry'
      preLoaderRoute: typeof AdminEntryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCodesRoute: typeof AdminCodesRoute
  AdminEntryRoute: typeof AdminEntryRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCodesRoute: AdminCodesRoute,
  AdminEntryRoute: AdminEntryRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  OrganiserRoute: OrganiserRoute,
  ScannerRoute: ScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
